version: 2
jobs:
    build-test:
        docker:
            - image: cypress/base:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: Start Server 
                command: npm run start:dist
                background: true
            - run:
                name: Sleep until server is up
                command: sleep 25
            - run:
                name: tests
                command: npm test
    deploy-production:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run: 
                name: Setup Git User
                command: git config --global user.email "circleci@localhost" && git config --global user.name "CircleCI"
            - run: 
                name: WorkAround for gh-pages
                command: cd node_modules/gulp-gh-pages/ && npm install --save gift@0.10.2 && cd ../../
            - deploy:
                name: Deploy to production
                command: npm run deploy
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-test:
                filters:
                    branches: 
                        ignore: gh-pages
            - deploy-production:
                requires:
                    - build-test
                filters:
                    branches:
                        only: master
