version: 2
jobs:
    build-test:
        docker:
            - image: cypress/base:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm run test-ci
    deploy-production:
        docker:
            - image: circleci/node:8
        steps:
            - deploy:
                name: Deploy to production
                command: npm run deploy
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-test:
                filters:
                    branches: 
                        ignore: gh-pages
            - deploy-production:
                requires:
                    - build-test
                filters:
                    branches:
                        only: master
