version: 2
jobs:
    build-v8:
        docker:
            - image: cypress/base:8
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: npm install
            - run:
                name: Security Audit
                command: npm audit
            - run:
                name: Start Server 
                command: npm run start:dist
                background: true
            - run:
                name: Sleep until server is up
                command: sleep 10
            - run:
                name: Test
                command: npm test
    build-v10:
        docker:
            - image: cypress/base:10
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: npm install
            - run:
                name: Security Audit
                command: npm audit
            - run:
                name: Start Server 
                command: npm run start:dist
                background: true
            - run:
                name: Sleep until server is up
                command: sleep 10
            - run:
                name: Test
                command: npm test
    deploy-production:
        docker:
            - image: circleci/node:10
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "3b:a6:7e:cb:94:8c:26:72:e2:52:c0:0f:9c:52:43:9d"
            - checkout
            - run:
                name: Install dependencies
                command: npm install --production
            - run: 
                name: Setup Git User
                command: git config --global user.email "circleci@localhost" && git config --global user.name "CircleCI"
            - run: 
                name: WorkAround for gh-pages
                command: cd node_modules/gulp-gh-pages/ && npm install --save gift@0.10.2 && cd ../../
            - deploy:
                name: Deploy to production
                command: npm run deploy
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-v8:
                filters:
                    branches: 
                        ignore: gh-pages
            - build-v10:
                filters:
                    branches: 
                        ignore: gh-pages
            - deploy-production:
                requires:
                    - build-v10
                    - build-v8
                filters:
                    branches:
                        only: master
