version: 2
jobs:
    start:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: Start Server 
                command: npm start &
                background: true
            - run:
                name: Wait 1s
                command: sleep 1
    build-test:
        docker:
            - image: cypress/base:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
    deploy-production:
        docker:
            - image: circleci/node:8
        steps:
            - deploy:
                name: Deploy to production
                command: npm run deploy
workflows:
    version: 2
    build-deploy:
        jobs:
            - start
            - build-test:
                requires:
                    - start
                filters:
                    branches: 
                        ignore: gh-pages
            - deploy-production:
                requires:
                    - build-test
                filters:
                    branches:
                        only: master
