name: Main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['12', '14']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        run: |
          npm ci
          npm run start:dist &
          sleep 10
          npm test
